// Purpose: Interface for Biker data model
export interface Biker {
    "id": number,
    "name": string,
    "nationality": string,
    "points": number,
    "leader": number,
    "previous": number,
    "qat": number,
    "ina": number,
    "arg": number,
    "ame": number,
    "por": number,
    "spa": number,
    "fra": number,
    "ita": number,
    "cat": number,
    "ger": number,
    "ned": number,
    "gbr": number,
    "aut": number,
    "rsm": number,
    "ara": number,
    "jpn": number,
    "tha": number,
    "aus": number,
    "mal": number,
    "val": number
}